blend_methods:
  euler:
    weight: 0.0
    decay_pattern: 'geometric'
    decay_mode: 'blend'
    tail_steps: 1

  euler_advanced:
    weight: 0.0
    decay_pattern: 'harmonic'
    decay_mode: 'blend'
    tail_steps: 1

  geometric:
    weight: 0.0
    decay_pattern: 'exponential'
    decay_mode: 'blend'
    tail_steps: 1

  harmonic:
    weight: 0.0
    decay_pattern: 'logarithmic'
    decay_mode: 'blend'
    tail_steps: 1

  logarithmic:
    weight: 0.5
    decay_pattern: 'fractional'
    decay_mode: 'blend'
    tail_steps: 1

  karras:
    weight: 0.0
    decay_pattern: 'exponential'
    decay_mode: 'blend'
    tail_steps: 1

  exponential:
    weight: 0.0
    decay_pattern: 'logarithmic'
    decay_mode: 'blend'
    tail_steps: 1

blending_style: 'softmax'
blending_mode: 'weights'