log_save_directory: "modules/sd_simple_kes/image_generation_data"
graph_save_directory: "modules/sd_simple_kes/image_generation_data"
graph_save_enable: false

skip_prepass: false # has no change to image quality - not currently functioning as intended for early stop purposes
device: "cuda" #cpu or cuda
debug: true
global_randomize: false
#
sigma_scale_factor: 900
sigma_auto_enabled: true
sigma_auto_mode: sigma_min # Options: sigma_min, sigma_max
#
rho_rand: false
rho_rand_min: 3.00 # tested recommended settings threshold
rho_rand_max: 8.00 # tested recommended settings threshold
#rho: 7.571656624637901
rho: 7.959565031107985
rho_enable_randomization_type: false
rho_randomization_type: "log"
rho_randomization_percent: 0.1
#
sigma_min_rand: false
sigma_min_rand_min: 0.001 # tested recommended settings 
sigma_min_rand_max: 0.02 # tested recommended settings threshold
sigma_min: 0.13757067353874633
sigma_min_enable_randomization_type: false
sigma_min_randomization_type:  "asymmetric"
sigma_min_randomization_percent: 0.2
#
sigma_max_rand: false
sigma_max_rand_min: 25 
sigma_max_rand_max: 60
sigma_max: 47.95768510805332
sigma_max_enable_randomization_type: false
sigma_max_randomization_type: "log"
sigma_max_randomization_percent: 0.25
#
start_blend_rand: false
start_blend_rand_min: 0.04 # tested recommended settings threshold
start_blend_rand_max: 0.11 # tested recommended settings threshold
start_blend: 0.08
start_blend_enable_randomization_type: false
start_blend_randomization_type:  "asymmetric"
start_blend_randomization_percent: 0.1
#
end_blend_rand: false
end_blend_rand_min: 0.4 # tested recommended settings threshold
end_blend_rand_max: 0.6 # tested recommended settings threshold
end_blend: 0.5
end_blend_enable_randomization_type: false
end_blend_randomization_type:  "asymmetric"
end_blend_randomization_percent: 0.2
#
sharpness_rand: false
sharpness_rand_min: 0.75 # tested recommended settings threshold
sharpness_rand_max: 0.95 # tested recommended settings threshold
sharpness: 0.85 # Note: Visible changes in image between 2-15. Above 15 - notable differences. At 50+ - poor image quality. sharpness not applied above 0.95
sharpen_variance_threshold: 0.01
sharpen_last_n_steps: 10
sharpen_mode: "full" # Options: last_n, full, both
sharpness_enable_randomization_type: false
sharpness_randomization_type:  "asymmetric"
sharpness_randomization_percent: 0.2
#
step_progress_mode: "linear" # Options supported (default = "linear"), "exponential", "logarithmic", or "sigmoid". If exponential, uses "exp_power"
exp_power: 2
#
initial_step_size_rand: false
initial_step_size_rand_min: 0.7 
initial_step_size_rand_max: 1.0 
initial_step_size: 0.9
initial_step_size_enable_randomization_type: false
initial_step_size_randomization_type: "asymmetric"
initial_step_size_randomization_percent: 0.2
#
final_step_size_rand: false
final_step_size_rand_min: 0.1
final_step_size_rand_max: 0.3
final_step_size: 0.20
final_step_size_enable_randomization_type: false
final_step_size_randomization_type:  "asymmetric"
final_step_size_randomization_percent: 0.2
#
step_size_factor_rand: false
step_size_factor_rand_min: 0.65
step_size_factor_rand_max: 0.85
step_size_factor: 0.80814932869181
step_size_factor_enable_randomization_type: false
step_size_factor_randomization_type:  "asymmetric"
step_size_factor_randomization_percent: 0.2
#
initial_noise_scale_rand: false
initial_noise_scale_rand_min: 1.0
initial_noise_scale_rand_max: 1.5
initial_noise_scale: 1.25
initial_noise_scale_enable_randomization_type: false
initial_noise_scale_randomization_type:  "asymmetric"
initial_noise_scale_randomization_percent: 0.2
#
final_noise_scale_rand: false
final_noise_scale_rand_min: 0.6
final_noise_scale_rand_max: 1.0
final_noise_scale: 0.80
final_noise_scale_enable_randomization_type: false
final_noise_scale_randomization_type:  "asymmetric"
final_noise_scale_randomization_percent: 0.2
#
smooth_blend_factor_rand: false
smooth_blend_factor_rand_min: 6
smooth_blend_factor_rand_max: 11
smooth_blend_factor: 9.426004103284665
smooth_blend_factor_enable_randomization_type: false
smooth_blend_factor_randomization_type:  "asymmetric"
smooth_blend_factor_randomization_percent: 0.2
#
noise_scale_factor_rand: false
noise_scale_factor_rand_min: 0.75
noise_scale_factor_rand_max: 0.95
noise_scale_factor: 0.8113992828873163
noise_scale_factor_enable_randomization_type: false
noise_scale_factor_randomization_type:  "asymmetric"
noise_scale_factor_randomization_percent: 0.2

# Experimental settings
early_stopping_threshold_rand: false
early_stopping_threshold_rand_min: 0.001
early_stopping_threshold_rand_max: 0.02
early_stopping_threshold: 0.06
early_stopping_method: max  # Options: mean, max, sum
sigma_variance_scale: 0.1   # *100 = % of current sigma, increase to reduce false early stopping, try 0.07 or 0.10
safety_minimum_stop_step: 10 # means won't consider until past this step, consider increasing this to increase minimum steps to process the image
recent_change_convergence_delta: 0.6 # this is the change between mean/max variable changes between sigmas. Keep this relatively low. This contributes directly to when we stop.
#min_visual_sigma: 50            # Increase from 10 to push later into the denoising sequence
early_stopping_threshold_enable_randomization_type: false
early_stopping_threshold_randomization_type: "asymmetric"
early_stopping_threshold_randomization_percent: 0.2
