device: "cuda"
debug: true
global_randomize: false
#
#randomization_type: asymmetric # Options: asymmetric, symmetric, exponential, or log #off is no longer a valid choice. Use the boolean flag for each variable to turn it on/off
#randomization_percent: 0.2 #Set to a decimal value
#
sigma_scale_factor: 200
sigma_auto_enabled: true
sigma_auto_mode: sigma_min # Options: sigma_min, sigma_max
#
rho_rand: true
rho_rand_min: 5.00
rho_rand_max: 10.00
rho: 7.571656624637901
rho_enable_randomization_type: false
rho_randomization_type: asymmetric
rho_randomization_percent: 0.2
#
sigma_min_rand: false
sigma_min_rand_min: 0.001
sigma_min_rand_max: 0.02
sigma_min: 0.13757067353874633
sigma_min_enable_randomization_type: false
sigma_min_randomization_type: asymmetric
sigma_min_randomization_percent: 0.2
#
sigma_max_rand: true
sigma_max_rand_min: 10  
sigma_max_rand_max: 50
sigma_max: 28.215968374619045
sigma_max_enable_randomization_type: false
sigma_max_randomization_type: asymmetric
sigma_max_randomization_percent: 0.25
#
start_blend_rand: false
start_blend_rand_min: 0.05
start_blend_rand_max: 0.2
start_blend: 0.10237033381422371
start_blend_enable_randomization_type: false
start_blend_randomization_type: asymmetric
start_blend_randomization_percent: 0.2
#
end_blend_rand: false
end_blend_rand_min: 0.4
end_blend_rand_max: 0.8
end_blend: 0.5627048166151302
end_blend_enable_randomization_type: false
end_blend_randomization_type: asymmetric
end_blend_randomization_percent: 0.2
#
sharpness_rand: false
sharpness_rand_min: 0.85
sharpness_rand_max: 1.0
sharpness: 0.9070742264431869
sharpness_enable_randomization_type: false
sharpness_randomization_type: asymmetric
sharpness_randomization_percent: 0.2
#
early_stopping_threshold_rand: false
early_stopping_threshold_rand_min: 0.001
early_stopping_threshold_rand_max: 0.02
early_stopping_threshold: 0.01
early_stopping_threshold_enable_randomization_type: false
early_stopping_threshold_randomization_type: asymmetric
early_stopping_threshold_randomization_percent: 0.2

#
initial_step_size_rand: false
initial_step_size_rand_min: 0.7
initial_step_size_rand_max: 1.0
initial_step_size: 0.9
initial_step_size_enable_randomization_type: false
initial_step_size_randomization_type: asymmetric
initial_step_size_randomization_percent: 0.2
#
final_step_size_rand: false
final_step_size_rand_min: 0.1
final_step_size_rand_max: 0.3
final_step_size: 0.20
final_step_size_enable_randomization_type: false
final_step_size_randomization_type: asymmetric
final_step_size_randomization_percent: 0.2
#
initial_noise_scale_rand: false
initial_noise_scale_rand_min: 1.0
initial_noise_scale_rand_max: 1.5
initial_noise_scale: 1.25
initial_noise_scale_enable_randomization_type: false
initial_noise_scale_randomization_type: asymmetric
initial_noise_scale_randomization_percent: 0.2
#
final_noise_scale_rand: false
final_noise_scale_rand_min: 0.6
final_noise_scale_rand_max: 1.0
final_noise_scale: 0.80
final_noise_scale_enable_randomization_type: false
final_noise_scale_randomization_type: asymmetric
final_noise_scale_randomization_percent: 0.2
#
smooth_blend_factor_rand: false
smooth_blend_factor_rand_min: 6
smooth_blend_factor_rand_max: 11
smooth_blend_factor: 9.426004103284665
smooth_blend_factor_enable_randomization_type: false
smooth_blend_factor_randomization_type: asymmetric
smooth_blend_factor_randomization_percent: 0.2
#
step_size_factor_rand: false
step_size_factor_rand_min: 0.65
step_size_factor_rand_max: 0.85
step_size_factor: 0.80814932869181
step_size_factor_enable_randomization_type: false
step_size_factor_randomization_type: asymmetric
step_size_factor_randomization_percent: 0.2
#
noise_scale_factor_rand: false
noise_scale_factor_rand_min: 0.75
noise_scale_factor_rand_max: 0.95
noise_scale_factor: 0.8113992828873163
noise_scale_factor_enable_randomization_type: false
noise_scale_factor_randomization_type: asymmetric
noise_scale_factor_randomization_percent: 0.2
