device: "cuda"
debug: true
global_randomize: false
rho_rand: false
rho_rand_min: 5.00
rho_rand_max: 10.00
rho: 8
sigma_min_rand: false
sigma_min_rand_min: 1.0
sigma_min_rand_max: 15.0
sigma_min: 1.7368178985090397
sigma_max_rand: false
sigma_max_rand_min: 15.0
sigma_max_rand_max: 45.0
sigma_max: 27.514134707749264
update_interval_rand: false
update_interval_rand_min: 5
update_interval_rand_max: 10
update_interval: 5.682264747470315
initial_step_size: 0.90
final_step_size: 0.20
initial_noise_scale: 1.25
final_noise_scale: 0.80
start_blend_rand: false
start_blend_rand_min: 0.05
start_blend_rand_max: 0.2
start_blend: 0.1
end_blend_rand: false
end_blend_rand_min: 0.4
end_blend_rand_max: 0.6
end_blend: 0.5627048166151302
sharpness_rand: false
sharpness_rand_min: 0.85
sharpness_rand_max: 1.0
sharpness: 0.9070742264431869
early_stopping_rand: false
early_stopping_rand_min: 0.001
early_stopping_rand_max: 0.02
early_stopping_threshold: 0.01
update_interval_rand: false
update_interval_rand_min: 5
update_interval_rand_max: 10
initial_step_rand: false
initial_step_rand_min: 0.7
initial_step_rand_max: 1.0
final_step_rand: false
final_step_rand_min: 0.1
final_step_rand_max: 0.3
initial_noise_rand: false
initial_noise_rand_min: 1.0
initial_noise_rand_max: 1.5
final_noise_rand: false
final_noise_rand_min: 0.6
final_noise_rand_max: 1.0
smooth_blend_factor_rand: false
smooth_blend_factor_rand_min: 6
smooth_blend_factor_rand_max: 11
smooth_blend_factor: 9.426004103284665
step_size_factor_rand: false
step_size_factor_rand_min: 0.65
step_size_factor_rand_max: 0.85
step_size_factor: 0.80814932869181
noise_scale_factor_rand: false
noise_scale_factor_rand_min: 0.75
noise_scale_factor_rand_max: 0.95
noise_scale_factor: 0.8113992828873163
